### ISSUE TITLE
6 - Students should be able to give notice about specific needs when applying for a seat

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#10]
- [x] Frontend #47 
- [x] Backend #46 

Funksjonell test:
Logg inn som student. Lag en ny søknad. Fyll inn behov for tilrettelegging. Se at søknaden din ble sendt med tilretteleggingsbehovet

**Comment by Paalar** [comment]
Functional test approved

**Comment by FluidSense** [comment]
Functional test approved
