### ISSUE TITLE
13 - Students should be able to apply for a waiting list if not given a seat in an application round

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#17]
Logg inn som student etter søknadsperioden. Søk som vanlig. Se at søknaden din havner i venteliste.

**Comment by Adrianht** [comment]
We solved this in a better way, communicated by the customer, than what the user story and following functional test specifies. Customer wanted to decide which applicants that should be added to the waiting list.

New functional test:
Log in as student. Create an application. Log in as admin. Approve the applications that received a seat in the round. Set the rest of the applications on the waiting list. Log in as student. See that you are on the waiting list.

**Comment by Adrianht** [comment]
> Log in as student. Create an application. Log in as admin. Approve the applications that received a seat in the round. Set the rest of the applications on the waiting list, including beforementioned student. Log in as student. See that you are on the waiting list.

^This funcitonal test is ok! 👌

**Comment by FluidSense** [comment]
That funcitonal test is OK! :ok_hand:
