### ISSUE TITLE
41 - As an admin i can see if a students has specific needs and what kind of needs

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#187]
Logg in som admin. Trykk på applikasjoner i sidepanelet. Se alle applikasjoner. Trykk på en applikasjon. Se i 'Needs' feltet om personen trenger tilrettelegging.

**Comment by Adrianht** [comment]
Functional test OK

**Comment by FluidSense** [comment]
Solved by #171

**Comment by FluidSense** [comment]
Functional test OK
