### ISSUE TITLE
43 - As an admin I can login through FEIDE

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#189]
Gå inn på applikasjonen. Logg inn med en konto med administratorrettigheter.

**Comment by Adrianht** [comment]
I feel like we need to add the correct BAS group before this passes the functional test.

**Comment by Adrianht** [comment]
Functional test OK! ❤️

**Comment by Adrianht** [comment]
Functional test OK! 🎉

**Comment by Paalar** [comment]
Client has done the functional test a long time ago!
