### ISSUE TITLE
16 - Admin should be able to set up a new application round

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#19]
- [x] Frontend #72 
 - [x] Backend #73 

Funksjonell test:
Logg inn som administrator. Velg panel for å lage ny søknadsrunde. Fyll inn tidspunkter for søknadsrunde. Submit søknadsrunder. Få bekreftelse på at den er satt opp. Se informasjon on den nye runden.

**Comment by FluidSense** [comment]
"Submit søkandsrunde" -> 401 Unathorized

**Comment by FluidSense** [comment]
Functional test OK

**Comment by Adrianht** [comment]
Function test OK
