### ISSUE TITLE
18 - Admin should be able to add and remove a room

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#21]
- [x] Frontend #74 
 - [x] Backend #75 

Funksjonell test:
Logg inn som administrator. Velg panel for saler. Legg til ny sal. Se at salen er laget. Fjern salen. Se at salen er borte.

**Comment by FluidSense** [comment]
403 - Unauthorized

**Comment by FluidSense** [comment]
Functional test OK

**Comment by Adrianht** [comment]
Functional test OK
