### ISSUE TITLE
Application does not scale perfectly on smaller screens

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#215]
1. We need a burger menu, so that you can go to the different paths in sidepanel
2. Veileder is a bit fucky wucky

(add more here when found)

**Comment by PeterRydberg** [comment]
Is this to be considered closed after communication with customer? As mobile is not a priority.

**Comment by Adrianht** [comment]
> Is this to be considered closed after communication with customer? As mobile is not a priority.

No. We do not close issues when they still need to be fixed, as there will most likely be continuous development on the project, after we're done.

**Comment by Adrianht** [comment]
Resolved by #324 and #336
