### ISSUE TITLE
Route changes application season display

### ISSUE THREAD

**Issue by FluidSense** [FluidSense/SeatMaster#218]
By spamming on the Home route, I notice that the status sometimes says Closed and Open at the same time. We fixed this, but for some reason, this is a weird bug.
It is not critical, as I think only seasons which open and close for applications on the same day are affected.

**Comment by Paalar** [comment]
Could you try to re-create this in current master?

**Comment by FluidSense** [comment]
The issue only exists if a season ends and opens as the same day, which is not possible to set through UI. Will therefore close.
