### ISSUE TITLE
19 - Admin should be able to add and remove seats for a given room

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#22]
- [x] Frontend #76 
 - [x] Backend #77

Funksjonell test:
Logg inn som administrator. Velg panel for saler. Velg en sal. Legg til en ny plass. Se at plassen dukker opp på salen. Fjern salplassen. Se at den forsvinner fra salen.

**Comment by Adrianht** [comment]
Functional test OK

**Comment by aslakhol** [comment]
Functional test OK
