### ISSUE TITLE
27 - Admin should be able to change students seats

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#29]
- [x] Frontend #78 
 - [x] Backend #79

Funksjonell test:
Logg inn som administrator. Velg side for rom. Trykk på et rom. Slett en student fra en plass. Slett en student fra den andre plassen. Legg til student på ny plass. Legg til andre student på andre plassen. Se at plassene blir oppdatert.

**Comment by Adrianht** [comment]
Functional test ok

**Comment by FluidSense** [comment]
# TODO:  

- [ ] Calls to backend
- [ ] Redirect & update

**Comment by Adrianht** [comment]
Functional test OK! #259

**Comment by Paalar** [comment]
Functinal test Ok!
