### ISSUE TITLE
28 - Admin should be able to remove a student from a seat 

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#30]
- [x] Frontend #80 
 - [x] Backend #81 

Funksjonell test:
Logg inn som administrator. Velg panel for plasser. Slett en student fra en plass. Se at plassen blir oppdatert til å ikke ha en student.

**Comment by FluidSense** [comment]
Hm, same issue as with assigning seats. The workflow does not match our functional test.

**Comment by Adrianht** [comment]
Functional test OK

**Comment by FluidSense** [comment]
Functional test OK
