### ISSUE TITLE
Updates to seats should be reflected in rooms.seats state

### ISSUE THREAD

**Issue by aslakhol** [FluidSense/SeatMaster#304]
When a seat is updated, created or deleted we should reflect this in the state through rooms.seats.seats  We already have actions for this we just need to use them in the viewRoomsreducer

**Comment by FluidSense** [comment]
This is not a problem after all, since everything happens on Save, including redirect to Rooms which fetches all rooms with updates!

**Comment by aslakhol** [comment]
eeeeh, not really. Changes to seats happen before save.

**Comment by aslakhol** [comment]
But I still think this is extremely low priority.

**Comment by aslakhol** [comment]
We've determined that there is no reasonable way to encounter an issue because of this so we'll close this issue.
