### ISSUE TITLE
Status is not changed on seat changes

### ISSUE THREAD

**Issue by FluidSense** [FluidSense/SeatMaster#318]
**Test case**
User 1 has seat A1 and is approved
User 2 has no seat and status is submitted
Assign seat A1 to User2
User 2 has seat A1 and status is submitted
User 1 has no seat and is approved!!!!!

Might make sense to set status to submitted backend, if a user loses their seat.
However, a user should still have status approved if changed seat between another approved with seat.

**Comment by aslakhol** [comment]
This also happens with waiting lists, and if you remove a seat from a person who is approved through the room.
