### ISSUE TITLE
32 - Admin should be able to give a specific seat to a specific student

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#35]
- [x] Frontend #82 
 - [x] Backend #83 

Funksjonell test:
Logg inn som administrator. Velg panel for saler. Velg en sal. Velg en plass. Tildel plass til student. Se at plass blir oppdatert med info til valgt student.

**Comment by Adrianht** [comment]
Function test OK, however done a bit differently ->
Logged in as Admin. Picked Applications in the panel. Picked an application. Picked a Room. Picked a Seat. Clicked submit. Saw that the seat was registered on the user when viewing the application again.

**Comment by Adrianht** [comment]
Functional test OK!

**Comment by FluidSense** [comment]
Functional test OK!
