### ISSUE TITLE
33 - Admin should be able to change a students application

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#36]
Logg inn som administrator. Velg en søknad. Trykk på endre. Endre informasjon. Se at søknad blir oppdatert.

**Comment by FluidSense** [comment]
Started work at 9864c6a.
**Needs**:
- [ ] Backend for editing application for admin
- [ ] Backend for editing application for user
- [ ] Frontend-Post for editing application for admin  
- [ ] Frontend-Post for editing application for user  
- [ ] Button to save edits for admin  
- [ ] Form to edit for user

**Comment by FluidSense** [comment]
Functional test OK!

**Comment by Paalar** [comment]
Functional test, ok!
