### ISSUE TITLE
37 - Student should be able to apply for a seat

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#39]
- [x] Frontend #50 
 - [x] Backend #49 

Funksjonell test:
Logg inn som student under en søknadsrunde. Lag en ny søknad. Fyll ut alle felter. Send inn søknad. Se at søknaden er registrert.

**Comment by Adrianht** [comment]
Functional test ok

**Comment by FluidSense** [comment]
Functional test ok
