### ISSUE TITLE
Create UI for users applying for seats next to eachother

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#45]
Students that are writing their master thesis in pairs should be able to apply for seats next to eachother.

- [x] Create a box where students can type in the other students name/stud.nr  
- [x] Hook it up to the backend
- [x] Create tests and pass them
     - [x] e2e
     - [x] Unit

**Comment by FluidSense** [comment]
@Adrianht Could you create the e2e-tests for this?
