### ISSUE TITLE
3 - Student should be able to give information about themselves

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#7]
- [x] Frontend #70 
 - [x] Backend #71 

Funksjonell test:
Logg inn som student. Lag ny søknad. Se at Feide henter og fyller inn data.

**Comment by PeterRydberg** [comment]
Closed since the wording of the title makes it technically finished, but reopened because it references an isue which requires master status to be implemented correctly.

**Comment by Adrianht** [comment]
Functional test OK

**Comment by FluidSense** [comment]
Functional test OK
