### ISSUE TITLE
4 - Students that write thesis together should be able to apply for a seat next to eachother

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#8]
- [x] Frontend #45 
- [x] Backend #44 

Funksjonell test:
Logg inn som student. Lag en ny søknad. Skriv inn brukernavn til personen du vil skrive med. Se etter du har søkt at søknaden din er koblet opp mot partneren sin.

**Comment by FluidSense** [comment]
Functional test approved

**Comment by Paalar** [comment]
Functional test approved
