### ISSUE TITLE
5 - Students should be able to apply for specific rooms

### ISSUE THREAD

**Issue by Adrianht** [FluidSense/SeatMaster#9]
Logg inn som student. Lag en ny søknad. Velg rom fra drop-down liste. Se at søknaden din inneholder romønske.

**Comment by PeterRydberg** [comment]
This one is kind of finished as you can send in applications with strings as a room object, but will be closed when actual room-fetch is implemented.

**Comment by Adrianht** [comment]
Functional test OK 💥

**Comment by FluidSense** [comment]
Functional test OK!
